# Top 10/10 by best macro F1 = 0.554605
# source run: PatchTST_Depth_Width_Search / pl32_s16_lr0.001_do0.2_L5_optadamw_h4_wd0p03_classifierlinear_jitter_prob0_shift_prob0_twarp_prob0_mwarp_prob0.3 (v28fcp2q)
patch_length: 32
stride: 16
num_channels: 3
lookback_window: 1024
num_batches: 128
loss: w_cross_entropy
epochs: 50
optimizer: adamw
lr: 0.001
weight_decay: 0.03
min_lr: 1.0e-09
scheduler: cosine_warmup
warmup_epochs: 5
d_model: 128
t_heads: 4
t_dim_feedforward: 256
t_dropout: 0.2
t_activation: gelu
t_num_layers: 5
mlp_hidden_size: 128
num_classes: 10
channel_independence: true
positional_encoding: rope
hook_attention_maps: false
output_dir: grid_top_10/
classifier: linear
jitter_prob: 0
shift_prob: 0
twarp_prob: 0
mwarp_prob: 0.3
run_type: validation
run_name: grid_top_10_phase2
