# Top 1/10 by best macro F1 = 0.567412
# source run: PatchTST_Depth_Width_Search / pl64_s16_lr0.001_do0.2_L3_optadamw_h16_wd0p01_classifierlinear_jitter_prob0_shift_prob0_twarp_prob0_mwarp_prob0 (d0ah09g0)
patch_length: 64
stride: 16
num_channels: 3
lookback_window: 1024
num_batches: 128
loss: w_cross_entropy
epochs: 50
optimizer: adamw
lr: 0.001
weight_decay: 0.01
min_lr: 1.0e-09
scheduler: cosine_warmup
warmup_epochs: 5
d_model: 128
t_heads: 16
t_dim_feedforward: 256
t_dropout: 0.2
t_activation: gelu
t_num_layers: 3
mlp_hidden_size: 128
num_classes: 10
channel_independence: true
positional_encoding: rope
hook_attention_maps: false
output_dir: grid_top_1/
classifier: linear
jitter_prob: 0
shift_prob: 0
twarp_prob: 0
mwarp_prob: 0.0
run_type: validation
run_name: grid_top_1_phase2
